version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - nic-lan
  labels:
  - dependencies
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: parser
    versions:
    - 3.0.1.0
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.9.0
    - 1.9.1
  - dependency-name: rspec-support
    versions:
    - 3.10.2
  - dependency-name: dry-schema
    versions:
    - 1.6.0
