require:
  - rubocop-rspec

Layout/LineLength:
  Max: 100

RSpec/MessageSpies:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
